name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
        include:
          - pytorch-version: 1.9.1
            python-version: 3.9
          - pytorch-version: 1.11.0
            python-version: '3.10'
          - pytorch-version: 2.5.1
            python-version: 3.9
          - pytorch-version: 2.5.1
            python-version: '3.10'
          
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install 'numpy<2'
        pip install torch==${{ matrix.pytorch-version }}+cpu -f https://download.pytorch.org/whl/torch
    - name: Hello World
      run: |
        echo 'Hello World!'
